<?php

declare(strict_types=1);

use Prometheus\Controllers\ActivityCategoryController;
use Prometheus\Controllers\AgentController;
use Prometheus\Controllers\AuthController;
use Prometheus\Controllers\AuditLogController;
use Prometheus\Controllers\BackupController;
use Prometheus\Controllers\ControlController;
use Prometheus\Controllers\DashboardController;
use Prometheus\Controllers\EventController;
use Prometheus\Controllers\IntegrityCheckController;
use Prometheus\Controllers\ReportController;
use Prometheus\Controllers\StatisticsController;
use Prometheus\Controllers\UserController;

$router->get('/', [DashboardController::class, 'index']);
$router->get('/login', [AuthController::class, 'showLogin']);
$router->get('/csrf-token', [AuthController::class, 'csrfToken']);
$router->get('/me', [AuthController::class, 'me']);
$router->post('/login', [AuthController::class, 'login']);
$router->post('/logout', [AuthController::class, 'logout']);
$router->get('/dashboard', [DashboardController::class, 'index']);
$router->get('/controls', [ControlController::class, 'index']);
$router->get('/controls/create', [ControlController::class, 'create']);
$router->post('/controls', [ControlController::class, 'store']);
$router->get('/controls/{control}', [ControlController::class, 'show']);
$router->get('/controls/{control}/edit', [ControlController::class, 'edit']);
$router->get('/controls/{control}/versions', [ControlController::class, 'versions']);
$router->put('/controls/{control}', [ControlController::class, 'update']);
$router->post('/controls/{control}/validate', [ControlController::class, 'validate']);
$router->post('/controls/{control}/annul', [ControlController::class, 'annul']);
$router->get('/events', [EventController::class, 'index']);
$router->post('/events', [EventController::class, 'store']);
$router->get('/events/{event}', [EventController::class, 'show']);
$router->put('/events/{event}', [EventController::class, 'update']);
$router->get('/activity-categories', [ActivityCategoryController::class, 'index']);
$router->post('/activity-categories', [ActivityCategoryController::class, 'store']);
$router->get('/activity-categories/{category}', [ActivityCategoryController::class, 'show']);
$router->put('/activity-categories/{category}', [ActivityCategoryController::class, 'update']);
$router->post('/activity-categories/{category}/deactivate', [ActivityCategoryController::class, 'deactivate']);
$router->get('/agents', [AgentController::class, 'index']);
$router->post('/agents', [AgentController::class, 'store']);
$router->get('/agents/{agent}', [AgentController::class, 'show']);
$router->put('/agents/{agent}', [AgentController::class, 'update']);
$router->post('/agents/{agent}/deactivate', [AgentController::class, 'deactivate']);
$router->get('/statistics', [StatisticsController::class, 'index']);
$router->get('/reports', [ReportController::class, 'index']);
$router->get('/reports/controls.csv', [ReportController::class, 'controlsCsv']);
$router->get('/reports/controls.xls', [ReportController::class, 'controlsXls']);
$router->get('/reports/controls.pdf', [ReportController::class, 'controlsPdf']);
$router->get('/reports/statistics.pdf', [ReportController::class, 'statisticsPdf']);
$router->get('/controls/{control}/pdf', [ControlController::class, 'pdf']);
$router->post('/profile/change-password', [UserController::class, 'profileChangePassword']);
$router->get('/users', [UserController::class, 'index']);
$router->post('/users', [UserController::class, 'store']);
$router->get('/users/{user}', [UserController::class, 'show']);
$router->put('/users/{user}', [UserController::class, 'update']);
$router->post('/users/{user}/deactivate', [UserController::class, 'deactivate']);
$router->post('/users/{user}/activate', [UserController::class, 'activate']);
$router->post('/users/{user}/change-password', [UserController::class, 'changePassword']);
$router->get('/audit-logs', [AuditLogController::class, 'index']);
$router->get('/backup', [BackupController::class, 'index']);
$router->post('/backup', [BackupController::class, 'store']);
$router->get('/integrity-check', [IntegrityCheckController::class, 'index']);
$router->post('/integrity-check', [IntegrityCheckController::class, 'store']);
