INSERT INTO activity_categories (name, description, active, created_at, updated_at) VALUES
('Minuta vendita', NULL, TRUE, NOW(), NOW()),
('Somministrazione alimenti e bevande', NULL, TRUE, NOW(), NOW()),
('Pubblici spettacoli', NULL, TRUE, NOW(), NOW()),
('Lidi balneari', NULL, TRUE, NOW(), NOW()),
('Strutture ricettive', NULL, TRUE, NOW(), NOW()),
('Case di cura', NULL, TRUE, NOW(), NOW()),
('Autonoleggio', NULL, TRUE, NOW(), NOW()),
('Istituti di vigilanza', NULL, TRUE, NOW(), NOW()),
('Istituti di investigazioni private', NULL, TRUE, NOW(), NOW()),
('Fabbriche di fuochi d''artificio', NULL, TRUE, NOW(), NOW()),
('Depositi di fuochi d''artificio', NULL, TRUE, NOW(), NOW()),
('Negozi di fuochi d''artificio', NULL, TRUE, NOW(), NOW()),
('Commercio preziosi', NULL, TRUE, NOW(), NOW()),
('Sale scommesse ex art. 88 TULPS', NULL, TRUE, NOW(), NOW()),
('Sale giochi ex art. 86 TULPS', NULL, TRUE, NOW(), NOW()),
('Controllo armi', NULL, TRUE, NOW(), NOW()),
('Armerie', NULL, TRUE, NOW(), NOW()),
('Controllo fuochi / aree di sparo', NULL, TRUE, NOW(), NOW());
